COLUNA_PRODUCT_ID = "product_id"
COLUNA_DATA = "data"
COLUNA_HORA = "hora"
COLUNA_DEPARTAMENTO = "departamento"
COLUNA_LATITUDE = "geolocation_lat"
COLUNA_LONGITUDE = "geolocation_lng"
PREFIXO_CEP_RAW = "geolocation_zip_code_prefix"
DEPARTAMENTOS=   ["moveis_sala",
      "eletronicos",
      "perfumaria",
      "dvds_blu_ray",
      "nan",
      "no df",
      "construcao_ferramentas_seguranca",
      "casa_conforto_2",
      "eletrodomesticos_2",
      "artes_e_artesanato",
      "pc_gamer",
      "moveis_decoracao",
      "musica",
      "alimentos_bebidas",
      "tablets_impressao_imagem",
      "eletroportateis",
      "telefonia",
      "pcs",
      "utilidades_domesticas",
      "cds_dvds_musicais",
      "fashion_roupa_masculina",
      "moveis_colchao_e_estofado",
      "moveis_quarto",
      "fashion_esporte",
      "informatica_acessorios",
      "artigos_de_festas"
      "esporte_lazer",
      "market_place",
      "casa_construcao",
      "telefonia_fixa",
      "eletrodomesticos",
      "industria_comercio_e_negocios",
      "portateis_cozinha_e_preparadores_de_alimentos",
      "bebidas",
      "consoles_games",
      "fashion_roupa_infanto_juvenil",
      "artigos_de_natal",
      "agro_industria_e_comercio",
      "portateis_casa_forno_e_cafe",
      "cine_foto",
      "brinquedos",
      "construcao_ferramentas_iluminacao",
      "fashion_roupa_feminina",
      "relogios_presentes",
      "fashion_bolsas_e_acessorios",
      "pet_shop",
      "construcao_ferramentas_construcao",
      "moveis_escritorio",
      "malas_acessorios",
      "beleza_saude",
      "alimentos",
      "automotivo",
      "flores",
      "livros_importados",
      "seguros_e_servicos",
      "sinalizacao_e_seguranca",
      "cool_stuff",
      "cama_mesa_banho",
      "bebes",
      "fashion_underwear_e_moda_praia",
      "moveis_cozinha_area_de_servico_jantar_e_jardim",
      "audio",
      "fraldas_higiene",
      "instrumentos_musicais",
      "casa_conforto",
      "papelaria",
      "livros_tecnicos",
      "la_cuisine",
      "climatizacao",
      "fashion_calcados",
      "livros_interesse_geral",
      "construcao_ferramentas_ferramentas",
      "ferramentas_jardim",
      "artes",
      "construcao_ferramentas_jardim"]
FEATURES=['preco', 'prazo', 'frete', 'product_description_lenght','product_photos_qty', 'coord_distance']	